language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest pytest-cov

script:
  - py.test --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
