language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest pytest-cov hypothesis

script:
  - py.test --cov=cartesian

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: ohjeah
  password: $PYPI_PW
  on:
    tags: true
    python: "3.6"
    all_branches: true
